---
title: "Assessing Model Convergence"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Assessing Model Convergence}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(bbsBayes)
library(ggplot2)
```

First make sure you have the BBS data downloaded
```{r}
have_bbs_data()
```

If not, install with `fetch_bbs_data()`
```{r, eval = !have_bbs_data()}
fetch_bbs_data()
```



Let's start by running a quick (and dirty) model looking at the Pacific Wren.

```{r}
m <- stratify(by = "bbs_cws", sample_data = TRUE) %>%
  prepare_data(min_year = 2009, max_year = 2018) %>%
  run_model(model = "first_diff",
            iter_sampling = 20, iter_warmup = 20, chains = 2)

```

Now we can calculate our convergence metrics
```{r, warning=FALSE}
conv <- convergence(m)
conv
```

Wow, there are a *lot* of variables here.

We can visualize this by transforming the data frame and using ggplot2

```{r}
tconv <- tidyr::pivot_longer(conv, cols = c(ess_bulk, ess_tail, rhat))

ggplot(data = tconv, aes(x = variable, y = value, colour = variable_type)) +
    geom_point() +
    facet_wrap(~name, scales = "free_y") +
    scale_colour_viridis_d(guide = FALSE)
```

