---
title: "Getting setup"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

```


## Get `cmdstanr`
<https://mc-stan.org/cmdstanr/>

```{r, eval = FALSE}
install.packages("pak")
options(repos = c(cmdstanr = "https://mc-stan.org/r-packages/", 
                  CRAN = "https://cloud.r-project.org"))
pak::pkg_install("cmdstanr")

```

## Get `CmdStan`

<https://mc-stan.org/cmdstanr/articles/cmdstanr.html>

```{r, eval = FALSE}
cmdstanr::check_cmdstan_toolchain()
cmdstanr::install_cmdstan()
```

### Checks

- Useful to include in model runs for reproducibility

```{r}
cmdstanr::cmdstan_path()
cmdstanr::cmdstan_version()
```


## Troubleshooting


```
Warning message:
In fun(libname, pkgname) :
  rgeos: versions of GEOS runtime 3.10.2-CAPI-1.16.0
and GEOS at installation 3.8.0-CAPI-1.13.1differ
```

```{r, eval = FALSE}
pak::pkg_remove("rgeos")
pak::pkg_install("rgeos")
```




