# common_docs ------------------
#' Common arguments and documentation for various functions
#'
#'
#' @param quiet Logical. Suppress progress messages? Default `FALSE`
#' @param min_year Numeric. Minimum year to use. Default (`NULL`) uses first
#'   year in data.
#' @param max_year Numeric. Maximum year to use. Default (`NULL`) uses first
#'   year in data.
#' @param indices List. Indices generated by `generate_indices()`
#'
#' Use `@inheritParams common_docs` to include the above in any function
#' documentation with a matching argument (will only include matching args)
#'
#' @section NatureCounts account:
#'   All public data is available with a username/password
#'   ([sign up](https://www.naturecounts.ca/nc/default/register.jsp)
#'   for a free NatureCounts account). However, to access private/semi-public
#'   projects/collections you must request access. See the Access and
#'   `request_id`s section for more information.
#'
#' @keywords internal
#' @name common_docs
NULL
