# common_docs ------------------
#' Common arguments and documentation for various functions
#'
#' @param level Character. Which type of BBS counts to use, "state" or "stop".
#'   Default "state".
#' @param release Numeric. Which yearly release to use, 2022 (including data
#'   through 2021 field season) or 2020 (including data through 2019). Default
#'   2022.
#' @param sf Spatial data frame. PLACEHOLDER
#' @param model Character. Type of model to use, must be one of "first_diff"
#'   (First Differences), "gam" (General Additive Model), "gamye" (General
#'   Additive Model with Year Effect), or "slope" (Slope model).
#' @param model_variant Character. Model variant to use, must be one of
#'   "nonhier" (Non-hierarchical), "hier" (Hierarchical; default), or "spatial"
#'   (Spatially explicit).
#' @param min_year Numeric. Minimum year to use. Default (`NULL`) uses first
#'   year in data.
#' @param max_year Numeric. Maximum year to use. Default (`NULL`) uses first
#'   year in data.
#'
#' @param strata_data List. Stratified data generated by `stratify()`
#' @param prepared_data List. Prepared data generated by `prepare_data()`.
#' @param spatial_data List. Spatial neighbourhoods generated by `prepare_spatial()`.
#' @param model_data List. Model data generated by `prepare_model()`.
#' @param model_output List. Model output generated by `run_model()`.
#' @param indices List. Indices generated by `generate_indices()`.
#' @param trends List. Trends generated by `generate_trends()`.
#'
#' @param variables Character vector. Specific variables (e.g.,
#'   `"strata_raw[1]"`) or variable types (e.g., `"strata_raw"`) for which to
#'   calculate metrics. If `NULL` (default) all variables are returned.
#' @param set_seed Numeric. If `NULL` (default) no seed is set. Otherwise an
#'   integer number to be used with `withr::with_seed()` internally to ensure
#'   reproducibility.
#' @param quiet Logical. Suppress progress messages? Default `FALSE`.
#'
#' @details
#' Use `@inheritParams common_docs` to include the above in any function
#' documentation with a matching argument (will only include matching args)
#'
#' @section NatureCounts account:
#'   All public data is available with a username/password
#'   ([sign up](https://www.naturecounts.ca/nc/default/register.jsp)
#'   for a free NatureCounts account). However, to access private/semi-public
#'   projects/collections you must request access. See the Access and
#'   `request_id`s section for more information.
#'
#' @keywords internal
#' @name common_docs
NULL
