# common_docs ------------------
#' Common arguments and documentation for various functions
#'
#' @param level Character. Which type of BBS counts to fetch, "state" or "stop".
#'   Defaults to "state".
#' @param release Numeric. Yearly release. Options are 2022 (default including
#'   data through 2021 field season) or 2020 (including data through 2019)
#' @param sf Spatial data frame. PLACEHOLDER
#' @param model Character. Type of model to use, must be one of "first_diff"
#'   (First Differences), "gam" (General Additive Model), "gamye" (General
#'   Additive Model with Year Effect), or "slope" (Slope model).
#' @param model_variant Character. Model variant to use, must be one of
#'   "nonhier" (Non-hierarchical), "hier" (Hierarchical), or "spatial"
#'   (Spatially explicit).
#' @param model_output List. Output of `run_model()`.
#' @param quiet Logical. Suppress progress messages? Default `FALSE`
#' @param min_year Numeric. Minimum year to use. Default (`NULL`) uses first
#'   year in data.
#' @param max_year Numeric. Maximum year to use. Default (`NULL`) uses first
#'   year in data.
#' @param indices List. Indices generated by `generate_indices()`
#' @param prepped_data List. Output of `prepare_data()`.
#' @param variables Character vector. Specific variables (e.g.,
#'   `"strata_raw[1]"`) or variable types (e.g., `"strata_raw"`) for which to
#'   calculate metrics. If `NULL` (default) all variables are returned.
#'
#' Use `@inheritParams common_docs` to include the above in any function
#' documentation with a matching argument (will only include matching args)
#'
#' @section NatureCounts account:
#'   All public data is available with a username/password
#'   ([sign up](https://www.naturecounts.ca/nc/default/register.jsp)
#'   for a free NatureCounts account). However, to access private/semi-public
#'   projects/collections you must request access. See the Access and
#'   `request_id`s section for more information.
#'
#' @keywords internal
#' @name common_docs
NULL
