#' Generate a dataframe of the stratum indices
#'
#' \code{generate_strata_indices} creates a data frame of indices by year,
#'   factored by each stratum. These indicies can be used to generate
#'   trajectory plots of the species for each strata.
#'
#' @param jags_mod JAGS list generated by \code{run_model}
#'
#' @return Data frame of 4 variables:
#'   \item{Year}{Year of particular index}
#'   \item{Index}{Strata-weighted count index}
#'   \item{Q25}{2.5\% quantile of strata-weighted indices}
#'   \item{Q975}{97.5\% quantile of strata-weighted indices}
#'   \item{Stratum}{Name of the stratum}
#'
#' @importFrom stats quantile
#'
#' @examples
#'
#' \dontrun{
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = "bcr")
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Wood Thrush",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the indices for each strata
#' strata_index <- generate_strata_indices(jags_mod = mod)
#' }
#'
#' @export
#'

generate_strata_indices <- function(jags_mod = NULL)
{
  if (is.null(jags_mod))
  {
    stop("No model output supplied to generate_strata_indices()."); return(NULL)
  }

  data_list <- extract_index_data(jags_mod = jags_mod)
  n <- data_list$n
  area_weights <- data_list$area_weights
  y_min = data_list$y_min
  y_max = data_list$y_max
  r_year = data_list$r_year

  n_samples <- dim(n)[1]
  n_strata <- dim(n)[2]
  strata_indices <- area_weights$num

  n_median <- apply(n, c(2,3), median)
  n_25 <- apply(n, c(2,3), stats::quantile, probs = 0.025)
  n_975 <- apply(n, c(2,3), stats::quantile, probs = 0.975)

  data_summary <- data.frame(Year = integer(),
                             Index = double(),
                             Q25 = double(),
                             Q975 = double(),
                             Stratum = character(),
                             stringsAsFactors = FALSE)

  for (i in strata_indices)
  {
    strat_summary <- data.frame(Year = seq(y_min:y_max),
                               Index = as.numeric(as.vector(n_median[i,])),
                               Q25 = as.numeric(as.vector(n_25[i,])),
                               Q975 = as.numeric(as.vector(n_975[i,])),
                               Stratum = area_weights[which(area_weights$num == i), ]$region)
    strat_summary$Year <- (strat_summary$Year - 1) + min(r_year)

    data_summary <- rbind(data_summary, strat_summary)
  }

  return(data_summary)
}
