#' Generate the continental trend
#'
#' \code{generate_cont_trend} calculates the geometric mean annual changes in population size.
#'
#' @param indices Continental indices generated by \code{generate_cont_indices}
#' @param min_year Minimum year to calculate trends from
#' @param max_year Maximum year to calculate trends to
#'
#' @return Numeric percentage of trend
#'
#' @examples
#'
#' \dontrun{
#' # After running a JAGS model, use that output to create trend data frame
#' cont_trend <- generate_cont_trend(indices = indices)
#' }
#'
#' @export
#'

generate_cont_trend <- function(indices = NULL,
                                min_year = NULL,
                                max_year = NULL)
{
  if (is.null(min_year))
  {
    min_year = min(indices$Year)
  }
  if (is.null(max_year))
  {
    max_year = max(indices$Year)
  }

  new_index <- indices[which(indices$Year == max_year), ]$Index
  old_index <- indices[which(indices$Year == min_year), ]$Index

  trend <- 100 * ((new_index/old_index)^(1/(max_year - min_year)) - 1)

  return(trend)
}
