#' Generate a map of trends by strata.
#'
#' \code{generate_map} allows you to generate a colour-coded map of species trends
#'   for each strata. Given indices generated by \code{generate_strata_indices}, this
#'   function will calculate percent change for either the entire survey time or a
#'   specified amount of time and will then shade in each stratum based on the percent
#'   change in that stratum.
#'
#' @param indices Dataframe of yearly stratum indices produced by
#'   \code{generate_strata_indices}
#' @param stratify_by How was the data stratified?
#' @param min_year Minimum year to plot
#' @param max_year Maximum year to plot
#'
#' @return spplot object
#'
#' @importFrom rgdal readOGR
#' @importFrom sp spplot
#'
#' @examples
#'
#' \dontrun{
#'}
#' @export
#'

generate_map <- function(indices = NULL,
                         stratify_by = NULL,
                         min_year = NULL,
                         max_year = NULL)
{
  map <- readOGR(dsn = system.file("maps",
                                   package = "bbsBayes"),
                 layer = maps[[stratify_by]],
                 verbose = FALSE)



  return(spplot(map))
}
