#' Generate a dataframe of the stratum trends
#'
#' \code{generate_strata_trends} creates a data frame of trends by year,
#'   factored by each stratum. These trends are calculated using the indices
#'   generated by \code{generate_strata_indices}.
#'
#' @param indices Stratum indices generated by \code{generate_strata_indices}
#' @param min_year Minimum year to calculate trends from
#' @param max_year Maximum year to calculate trends to
#'
#' @return Data frame of 2 variables:
#'   \item{Stratum}{Name of the stratum}
#'   \item{Trend}{Percent change from the minimum year to maximum year}
#'
#' @examples
#'
#' \dontrun{
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = "bcr")
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Barn Swallow",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the indices for each strata
#' strata_index <- generate_strata_indices(jags_mod = mod)
#'
#' # Get the data frame of trends by strata
#' trend <- generate_strata_trends(indices = strata_index)
#' }
#'
#' @export
#'

generate_strata_trends <- function(indices = NULL,
                                   min_year = NULL,
                                   max_year = NULL)
{
  strata_used <- as.character(unique(indices$Stratum))
  if (is.null(min_year))
  {
    min_year = min(indices$Year)
  }
  if (is.null(max_year))
  {
    max_year = max(indices$Year)
  }

  trend <- NULL
  for (i in strata_used)
  {
    temp <- indices[which(indices$Stratum == i), ]
    new_index <- temp[which(temp$Year == max_year), ]$Index
    old_index <- temp[which(temp$Year == min_year), ]$Index

    trend_strata <- 100 * ((new_index/old_index)^(1/(max_year - min_year)) - 1)
    trend <- c(trend, trend_strata)
  }

  to_return <- as.data.frame(cbind(strata_used, trend))
  names(to_return) <- c("Stratum", "Trend")

  return(to_return)
}
