#' Generate trend indices for a given species.
#'
#' Generates yearly indices for the specified bird species
#'   given simulated MCMC chains.
#'
#' @param jags_mod JAGS list generated by \code{run_model}
#' @param stratify_by How was the data stratified?
#' @param plot_strata Which strata would you like to include in the list
#'   of plots? Provide a list of strata to plot or the string "all"
#'   to plot all the strata used in the analysis.
#'
#' @return List of ggplot2 objects
#'
#' @examples
#'
#' \dontrun{
#' }
#'
#' @importFrom utils read.csv
#' @export
#'

generate_trend_plot <- function(jags_mod = NULL,
                           stratify_by = NULL,
                           plot_strata = NULL)
{
  # Read area weights
  all_area_weights <- read.csv(system.file("area-weight", strata[[stratify_by]], package = "bbsBayes"))

  # Extract posterior data and other data from jags_mod
  n <- jags_mod$sims.list$n
  bugs_data <- jags_mod$model$data()
  y_min <- bugs_data$ymin
  y_max <- bugs_data$ymax

  # Subset area weights based on strata used and ensure same order as JAGS
  strata_used <- unique(jags_mod$strat_name)
  area_weights <- all_area_weights[which(all_area_weights$region %in% strata_used), ]
  area_weights <- area_weights[ order(match(area_weights$region, strata_used)),]

  cont <- plot_continental(n = n,
                           area_weights = area_weights,
                           y_min = y_min,
                           y_max = y_max)

  return(cont)

}
