#' Generate trend indices for a given species.
#'
#' Generates yearly indices for the specified bird species
#'   given simulated MCMC chains.
#'
#' @param jags_mod JAGS list generated by \code{run_model}
#' @param strata_to_plot Which strata would you like to include in the list
#'   of plots? Provide a list of strata to plot or the string "all"
#'   to plot all the strata used in the analysis.
#' @param cont Should a continental plot be produced?
#' @param ... Other arguments
#'
#' @return List of ggplot2 objects
#'
#' @examples
#'
#' \dontrun{
#' # Given we've run all stratification and prep functions, run model
#' jags_mod <- run_model(jags_data = data_jags,
#'                       model = "standard")
#'
#' # Generate continental plots only
#' plots <- generate_trend_plot(jags_mod = jags_mod)
#'
#' # Generate continental trend plots and trend plots for all strata
#' plots <- generate_trend_plot(jags_mod = jags_mod,
#'                              strata_to_plot = "all")
#'
#' # Generate continental trend plots and trend plots for specific strata
#' plots <- generate_trend_plot(jags_mod = jags_mod,
#'                              strata_to_plot = c("US-GA-27", "US-FL-31"))
#'
#' # Don't generate a continental plot
#' plots <- generate_trend_plot(jags_mod = jags_mod,
#'                              strata_to_plot = "all",
#'                              cont = FALSE)
#'
#'
#' }
#'
#' @importFrom utils read.csv
#' @export
#'

generate_trend_plot <- function(jags_mod = NULL,
                           strata_to_plot = NULL,
                           cont = TRUE,
                           ...)
{
  # Read area weights
  stratify_by <- jags_mod$stratify_by
  all_area_weights <- read.csv(system.file("area-weight", strata[[stratify_by]], package = "bbsBayes"))

  # Extract posterior data and other data from jags_mod
  n <- jags_mod$sims.list$n
  bugs_data <- jags_mod$model$data()
  y_min <- bugs_data$ymin
  y_max <- bugs_data$ymax

  # Subset area weights based on strata used and ensure same order as JAGS
  strata_used <- unique(jags_mod$strat_name)
  area_weights <- all_area_weights[which(all_area_weights$region %in% strata_used), ]
  area_weights <- area_weights[ order(match(area_weights$region, strata_used)),]

  if (isTRUE(cont))
  {
    cont_plot <- plot_continental(n = n,
                             area_weights = area_weights,
                             y_min = y_min,
                             y_max = y_max)
  }else
  {
    cont_plot = NULL
  }

  strata_plots <- plot_strata(n = n,
                              strata_to_plot = strata_to_plot,
                              area_weights = area_weights,
                              y_min = y_min,
                              y_max = y_max)

  return(list(cont_plot = cont_plot,
              strata_plot = strata_plots))

}
