#' Generate a map of trends by strata.
#'
#' \code{generate_map} allows you to generate a colour-coded map of species trends
#'   for each strata. Given trends generated by \code{generate_strata_trends}, this
#'   function will shade in each stratum based on the percent
#'   change in that stratum.
#'
#' @param trend Dataframe of strata trends produced by
#'   \code{generate_strata_trends}
#' @param stratify_by How was the data stratified?
#'
#' @return spplot object
#'
#' @importFrom rgdal readOGR
#' @importFrom sp spplot sp.polygons
#'
#' @examples
#'
#' \dontrun{
#' # Set stratification type for future use
#' stratification <- "bcr"
#'
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = stratification)
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Wood Thrush",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the indices for each strata
#' strata_index <- generate_strata_indices(jags_mod = mod)
#'
#' # Get the data frame of trends by strata
#' trend <- generate_strata_trends(indices = strata_index)
#'
#' # Obtain a map of the trends by each strata
#' map <- generate_map(trend = trend, stratify_by = stratification)
#' }
#' @export
#'

generate_map <- function(trend = NULL,
                         stratify_by = NULL)
{
  Trend <- NULL
  rm(Trend)

  map <- rgdal::readOGR(dsn = system.file("maps",
                                   package = "bbsBayes"),
                 layer = maps[[stratify_by]],
                 verbose = FALSE)
  breaks <- c(-7, -4, -2, -1, -0.5, 0.5, 1, 2, 4, 7)
  map@data$row_num <- 1:nrow(map@data)
  map@data <- merge(map@data, trend, by.x = "ST_12", by.y = "Region", all = T)
  map@data <- map@data[order(map@data$row_num), ]
  map@data$Trend <- as.numeric(as.character(map@data$Trend))
  map@data$Trend <- cut(map@data$Trend, breaks = c(-Inf, breaks, Inf))
  map@data <- subset(map@data, select = c(Trend))

  map_palette <- c("#a50026", "#d73027", "#f46d43", "#fdae61", "#fee090", "#ffffbf",
                   "#e0f3f8", "#abd9e9", "#74add1", "#4575b4", "#313695")

  return(sp::spplot(map, col.regions = map_palette))
}
