#' Generate trend indices for a given species.
#'
#' Generates yearly indices for the specified bird species
#'   given simulated MCMC chains
#'
#' @param jags_data List generated by \code{run_model} containing the JAGS model
#'   and MCMC samples
#' @param stratify_by How was the data stratified?
#'
#' @return
#'
#' @examples
#'
#' \dontrun{
#' }
#'
#' @importFrom utils read.csv
#' @export
#'

generate_trend <- function(jags_data = NULL,
                           stratify_by = NULL)
{

}
