#' Generate a dataframe of the regional yearly indices
#'
#' \code{generate_regional_indices} creates a data frame of the strata-weighted
#'   regional indices by year. This data frame can then be used to
#'   generate a population trajectory of the species.
#'
#' @param jags_mod JAGS list generated by \code{run_model} using either "bbs_cws" or "bbs_usgs" stratifications
#' @param quantiles vector of quantiles to be sampled from the posterior distribution Defaults to c(0.025,0.05,0.25,0.5,0.75,0.95,0.975)
#' @param regions vector selcting regional compilation(s) to calculate, options include "national", "prov_state", or "bcr", or any combination of these three
#'
#' @return List of 6 objects:
#'   \item{data_summary}{dataframe with the following columns}
#'   \item{Year}{Year of particular index}
#'   \item{Region}{Region name}
#'   \item{Index}{Strata-weighted count index}
#'   \item{additional columns for each of the values in quantiles}{quantiles of the posterior distribution}
#'   \item{samples}{array of all samples from the posterior distribution}
#'   \item{area-weights}{data frame of the strata names and area weights used to calculate the continental estimates}
#'   \item{y_min}{first year used in the model, scale 1:length of time-series}
#'   \item{y_max}{last year used in the model, scale 1:length of time-series}
#'   \item{startyear}{first year used in the model, scale 1966:2018}
#'
#' @importFrom stats quantile
#'
#' @examples
#'
#' \dontrun{
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = "bcr")
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Wood Thrush",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the continental indices weighted by each strata
#' cont_index <- generate_cont_indices(jags_mod = mod)
#' }
#'
#' @export
#'

generate_regional_indices <- function(jags_mod = NULL,
                                  quantiles = c(0.025,0.05,0.25,0.75,0.95,0.975),
                                  regions = c("national", "prov_state","bcr"))
{
  if (is.null(jags_mod))
  {
    stop("No model output supplied to generate_regional_indices()."); return(NULL)
  }

  data_list <- extract_index_data(jags_mod = jags_mod)
  stratify_by = jags_mod$stratify_by
  n <- data_list$n
  area_weights <- data_list$area_weights
  y_min = data_list$y_min
  y_max = data_list$y_max
  r_year = data_list$r_year

  bugs_data = data_list$bugs_data

  raw = data.frame(year = bugs_data$year,
                   count = bugs_data$count,
                   strat = bugs_data$strat)
  non_zero_weight = bugs_data$nonzeroweight

  n_samples <- dim(n)[1]


  region_names <- utils::read.csv(system.file("composite-regions", strata[[stratify_by]], package = "bbsBayes"),stringsAsFactors = F)
  #region_names <- read.csv(paste0("C:/Users/smithac/Documents/GitHub/temp/composite-regions/stratcan.csv"),stringsAsFactors = F)
  region_names$region = factor(region_names$region,levels = levels(area_weights$region))


  data_summary <- data.frame(Year = integer(),
                              Region = character(),
                              Region_alt = character(),
                             Region_type = character(),
                              Strata_included = character(),
                              Strata_excluded = character(),
                              Index = double(),
                             stringsAsFactors = F)
  for(qq in quantiles){
    data_summary[,paste0("Index_q_",qq)] <- double()
  }


  data_summary$obs_mean <- double()
  data_summary$nrts <- integer()
  data_summary$nnzero <- integer()

  N_all <- list()
  n_index <- 0
  for(rr in regions){ #selecting the type of composite region

    rrall = unique(region_names[,rr]) #list of composite regions of type rr
    if(rr == "national"){col_region_name <- "Country"}
    if(rr == "prov_state"){col_region_name <- "Province_State"}
    if(rr == "bcr"){col_region_name <- rr}

    for(rrs in rrall){ # for each of the composite regions

      region_alt_name = as.character(unique(region_names[which(region_names[,rr] == rrs),col_region_name]))
  if(rr == "bcr"){region_alt_name = paste("BCR",region_alt_name,sep = "_")}

st_sel = as.character(region_names[which(region_names[,rr] == rrs),"region"])
st_rem = NULL
strata_sel = area_weights[which(area_weights$region %in% st_sel),"num"]

if(length(strata_sel)<1){next}


obs_df = data.frame(year = integer(),
                    strat = integer(),
                    obs_mean = double(),
                    nrts = integer(),
                    nnzero = integer())

  for (j in strata_sel)
  {
    rawst <- raw[which(raw$strat == j),c("year","count")]
    yrs <- data.frame(year = c(y_min:y_max))
    rawst <- merge(rawst,yrs,by = "year",all = T)
    rawst <- rawst[order(rawst$year),]

    o_mns <- as.numeric(by(rawst[,2],INDICES = rawst[,1],FUN = mean,na.rm = T))
    nrts <- as.numeric(by(rawst[,2],INDICES = rawst[,1],FUN = length))
    nnzero <- as.numeric(by(rawst[,2],INDICES = rawst[,1],FUN = function(x){length(which(x>0))}))
    if(sum(nnzero[1:5]) < 1){st_rem <- c(st_rem,as.character(area_weights[which(area_weights$num == j),"region"]))
    if(length(strata_sel) == 1){break}
    next} #if no observations of the species in the first 5 years, then remove the strata from trend summaries
    obs_df_t <- data.frame(year = c(y_min:y_max),
                           strat = j,
                           obs_mean = o_mns*((area_weights$area_sq_km[which(area_weights$num == j)])/ sum(area_weights[which(area_weights$num %in% strata_sel),"area_sq_km"]))*(non_zero_weight[j]),
                           nrts = nrts,
                           nnzero = nnzero)

    obs_df <- rbind(obs_df,obs_df_t)
  }


if(!is.null(st_rem)){
  strata_sel = strata_sel[-which(strata_sel %in% area_weights[which(area_weights$region %in% st_rem),"num"])]
}

if(length(strata_sel)<1){next}

n_weight <- n
  # Weight each sampled n
  for (i in 1:n_samples)
  {
    for (j in strata_sel)
    {
      n_weight[i,j,] <- (n_weight[i,j,] * area_weights$area_sq_km[which(area_weights$num == j)])/ sum(area_weights[which(area_weights$num %in% strata_sel),"area_sq_km"])
    }
  }
n_weight <- n_weight[,strata_sel,]

  if(length(strata_sel) > 1){
      N <- apply(n_weight, c(1,3),sum)
    }else{
      N <- n_weight
}
  n_index <- n_index+1
  N_all[[n_index]] <- N
  names(N_all)[n_index] <- paste(rr,rrs,sep = "_")

  n_median <- apply(N, 2, median)
  data_summaryr <- data.frame(Year = seq(y_min:y_max),
                              Region = rrs,
                              Region_alt = region_alt_name,
                              Region_type = rr,
                              Strata_included = paste(st_sel,collapse = " ; "),
                              Strata_excluded = paste(st_rem,collapse = " ; "),
                              Index = n_median,
                              stringsAsFactors = F)
  for(qq in quantiles){
    data_summaryr[,paste0("Index_q_",qq)] <- apply(N,2,stats::quantile,probs = qq)
  }

  data_summaryr$Year <- as.integer((data_summaryr$Year - 1) + min(r_year))
  data_summaryr$obs_mean <- as.numeric(by(obs_df[,3],INDICES = obs_df[,1],FUN = sum,na.rm = T))
  data_summaryr$nrts <- as.numeric(by(obs_df[,4],INDICES = obs_df[,1],FUN = sum,na.rm = T))
  data_summaryr$nnzero <- as.numeric(by(obs_df[,5],INDICES = obs_df[,1],FUN = sum,na.rm = T))

  data_summary = rbind(data_summary,data_summaryr)


    }
  }


   return(list(data_summary = data_summary,
              samples = N_all,
              area_weights = area_weights,
              y_min = y_min,
              y_max = y_max,
              startyear = min(r_year),
              regions = regions))
}
