#' Generate a map of trends by strata.
#'
#' \code{generate_map} allows you to generate a colour-coded map of species trends
#'   for each strata. Given trends generated by \code{generate_strata_trends}, this
#'   function will shade in each stratum based on the percent
#'   change in that stratum.
#'
#' @param trend Dataframe of strata trends produced by
#'   \code{generate_strata_trends}
#' @param stratify_by How was the data stratified?
#'
#' @return spplot object
#'
#' @importFrom rgdal readOGR
#' @importFrom sp spplot
#' @importFrom grDevices colorRampPalette
#'
#' @examples
#'
#' \dontrun{
#' # Set stratification type for future use
#' stratification <- "bcr"
#'
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = stratification)
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Barn Swallow",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the indices for each strata
#' strata_index <- generate_strata_indices(jags_mod = mod)
#'
#' # Get the data frame of trends by strata
#' trend <- generate_strata_trends(indices = strata_index)
#'
#' # Obtain a map of the trends by each strata
#' map <- generate_map(trend = trend, stratify_by = stratification)
#' }
#' @export
#'

generate_map <- function(trend = NULL,
                         stratify_by = NULL)
{
  map <- readOGR(dsn = system.file("maps",
                                   package = "bbsBayes"),
                 layer = maps[[stratify_by]],
                 verbose = FALSE)
  map@data <- merge(map@data, trend, by.x = "St_12", by.y = "Stratum", all = T)
  map@data$Trend <- as.numeric(as.character(map@data$Trend))
  map@data <- subset(map@data, select = c(Trend))

  n_half <- 500
  col_neg <- colorRampPalette(colors = c("blue", "white"), space = "Lab")(n_half)
  col_pos <- colorRampPalette(colors = c("white", "red"), space = "Lab")(n_half)
  map_palette <- c(col_neg, col_pos)

  return(spplot(map, col.regions = map_palette))
}
