#' Generate R Markdown report
#'
#' Generates an R Markdown dashboard report that allows you to
#'   explore all trend plots generated as well as MCMC diagnostics.
#'
#' @param jags_mod JAGS list generated by \code{run_model}
#' @param ... Other arguments
#'
#' @return List of ggplot2 objects
#'
#' @examples
#'
#' \dontrun{
#' }
#'
#' @importFrom utils read.csv
#' @export
#'

generate_rmd_report <- function(jags_mod = NULL,
                                output_dir = getwd(),
                                ...)
{
  # Read area weights
  stratify_by <- jags_mod$stratify_by
  all_area_weights <- read.csv(system.file("area-weight", strata[[stratify_by]], package = "bbsBayes"))

  # Extract posterior data and other data from jags_mod
  n <- jags_mod$sims.list$n
  bugs_data <- jags_mod$model$data()
  y_min <- bugs_data$ymin
  y_max <- bugs_data$ymax

  # Subset area weights based on strata used and ensure same order as JAGS
  strata_used <- unique(jags_mod$strat_name)
  area_weights <- all_area_weights[which(all_area_weights$region %in% strata_used), ]
  area_weights <- area_weights[ order(match(area_weights$region, strata_used)),]

  rmarkdown::render(system.file("bbsBayes-report.Rmd", package = "bbsBayes"),
                    output_dir = output_dir,
                    params = list(n = n,
                                  area_weights = area_weights,
                                  y_min = y_min,
                                  y_max = y_max))


}
