#' Generate a dataframe of the continental yearly indices
#'
#' \code{generate_cont_indices} creates a data frame of the strata-weighed
#'   continental indices by year. This data frame can then be used to
#'   generate a population trajectory of the species.
#'
#' @param jags_mod JAGS list generated by \code{run_model}
#' @param quantiles vector of quantiles to be sampled from the posterior distribution Defaults to c(0.025,0.05,0.25,0.5,0.75,0.95,0.975)
#'
#' @return Data frame of 4 variables:
#'   \item{Year}{Year of particular index}
#'   \item{Index}{Strata-weighted count index}
#'   \item{Q25}{2.5\% quantile of strata-weighted indices}
#'   \item{Q975}{97.5\% quantile of strata-weighted indices}
#'
#' @importFrom stats quantile
#'
#' @examples
#'
#' \dontrun{
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = "bcr")
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Wood Thrush",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the continental indices weighted by each strata
#' cont_index <- generate_cont_indices(jags_mod = mod)
#' }
#'
#' @export
#'

generate_cont_indices <- function(jags_mod = NULL,
                                  quantiles = c(0.025,0.05,0.25,0.75,0.95,0.975))
{
  if (is.null(jags_mod))
  {
    stop("No model output supplied to generate_cont_indices()."); return(NULL)
  }

  data_list <- extract_index_data(jags_mod = jags_mod)
  n <- data_list$n
  area_weights <- data_list$area_weights
  y_min = data_list$y_min
  y_max = data_list$y_max
  r_year = data_list$r_year

  n_samples <- dim(n)[1]
  n_strata <- dim(n)[2]
  n_weight <- n

  # Weight each sampled n
  for (i in 1:n_samples)
  {
    for (j in 1:n_strata)
    {
      n_weight[i,j,] <- (n_weight[i,j,] * area_weights$area_sq_km[which(area_weights$num == j)])/ sum(area_weights$area_sq_km)
    }
  }

  N = apply(n_weight, c(1,3),sum)


  n_median <- apply(N, 2, median)
  data_summary <- data.frame(Year = seq(y_min:y_max),
                             Index = n_median)
  for(qq in quantiles){
  data_summary[,paste0("q_",qq)] <- apply(N,2,stats::quantile,probs = qq)
  }

  data_summary$Year <- (data_summary$Year - 1) + min(r_year)

  return(data_summary = data_summary,samples = N,area_weights = area_weights,y_min = y_min,y_max = y_max,startyear = min(r_year))
}
