#' Generate a geofacet plot of population trajectories by province/state
#'
#' \code{geofacet_plot} allows you to generate a faceted plot of population trajectories
#'   for each strata by province/state. Given a model stratified by "state", "bbs_cws", or "bbs_usgs"
#'   and indices generated by \code{generate_strata_indices} or \code{generate_regional_indices}, this
#'   function will generate a faceted plot showing the population trajectories. All geofacet plots have
#'   one facet per state/province, so if strata-level indices from the "bbs_cws" or "bbs_usgs" are given,
#'   the function plots multiple trajectories (one for each of the relevant strata) within each facet.
#'
#' @param indices_list Dataframe of strata or state/province indices produced by
#'   \code{generate_strata_indices} or \code{generate_regional_indices}
#' @param stratify_by How were the data stratified?
#' @param multiple Logical, if TRUE, multiple strata-level trajectories are plotted within each prov/state facet
#' @param trends Optional dataframe of matching strata or state/province trends produced by
#'   \code{generate_strata_trends} or \code{generate_regional_trends}. If included trajectories are coloured based on the same
#'   colour scale used in \code{generate_map}
#' @param slope Optional Logical, if dataframe of trends is included, colours in the plot are based on slope trends, Default = FALSE
#' @param add_observed_means Should the facet plots include points indicating the observed mean counts. Defaults to FALSE.  Note: scale of observed means and annual indices may not match due to imbalanced sampling among strata
#' @param species Species name to be added onto the plot
#' @param ci_width quantile to define the width of the plotted credible interval. Defaults to 0.95, lower = 0.025 and upper = 0.975
#'
#'
#'
#' @return ggplot object
#'
#' @importFrom ggplot2 ggplot theme element_blank element_line
#' labs geom_line geom_ribbon aes element_text element_rect
#' @importFrom grDevices grey
#' @importFrom geofacet facet_geo
#' @importFrom ggrepel geom_text_repel
#'
#' @examples
#'
#' \dontrun{
#' # Set stratification type for future use
#' stratification <- "bbs_cws"
#'
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = stratification)
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Canada Warbler",
#'                                   model = "gam")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the indices for each strata
#' strata_index <- generate_strata_indices(jags_mod = mod)
#'
#' # Get the data frame of trends by strata
#' trend <- generate_strata_trends(indices = strata_index)
#'
#' # Obtain a map of the trends by each strata
#' map <- geofacet_plot(indices = strata_index, trend = trend, stratify_by = stratification)
#' }
#' @export
#'



geofacet_plot <- function(indices_list = NULL,
                          stratify_by = NULL,
                          ci_width = 0.95,
                          multiple = FALSE,
                          trends = NULL,
                          slope = FALSE,
                          add_observed_means = FALSE,
                          species = ""){

  if (is.null(stratify_by))
  {
    stop("Argument stratify_by is empty."); return(NULL)
  }

  if (is.null(indices_list))
  {
    stop("Argument indices_list is empty. Please supply indices from generate_strata_indices() or generate_regional_indices()"); return(NULL)
  }


  facets <- utils::read.csv(system.file("geofacet-grids", strata[[stratify_by]], package = "bbsBayes"),stringsAsFactors = F)

  indices = indices_list$data_summary

  lq = (1-ci_width)/2
  uq = ci_width+lq
  lqc = paste0("Index_q_",lq)
  uqc = paste0("Index_q_",uq)


  indices$lci = indices[,lqc]
  indices$uci = indices[,uqc]


  mny = min(indices$Year)
  mxy = max(indices$Year)
  yys = pretty(seq(mny, mxy))
  yys = c(yys[-length(yys)],mxy)



  if(!is.null(trends)){


  breaks <- c(-7, -4, -2, -1, -0.5, 0.5, 1, 2, 4, 7)
  # map@data$row_num <- 1:nrow(map@data)
  # map@data <- merge(map@data, trend, by.x = "ST_12", by.y = "Region", all = T)
  # map@data <- map@data[order(map@data$row_num), ]
  if(slope){
    trends$Trend <- as.numeric(as.character(trends$Slope_Trend))
  }else{
    trends$Trend <- as.numeric(as.character(trends$Trend))
  }
  trends$Trend <- cut(map@data$Trend, breaks = c(-Inf, breaks, Inf))
  #map@data <- subset(map@data, select = c(Trend))

  map_palette <- c("#a50026", "#d73027", "#f46d43", "#fdae61", "#fee090", "#ffffbf",
                   "#e0f3f8", "#abd9e9", "#74add1", "#4575b4", "#313695")

  }
  if(add_observed_means){

  ptraj <- ggplot2::ggplot(data = indices) +
    ggplot2::theme(panel.grid.major = ggplot2::element_blank(),
          panel.grid.minor = ggplot2::element_blank(),
          panel.background = ggplot2::element_blank(),
          axis.text = ggplot2::element_text(colour = grey(0.2)),
          strip.background = ggplot2::element_rect(fill = grey(0.97)),#strcol #, colour = grey(0.9), size = NULL, linetype = NULL, color = NULL, inherit.blank = FALSE
          #axis.line = element_line(colour = "black"),
          legend.position = "none") +
    ggplot2::labs(title = paste(species,"trajectories within Provinces and States"), x = "Year", y = "Annual indices") +

    ggplot2::geom_point(data = to_plot,ggplot2::aes(x = Year,y = obs_mean),colour = grDevices::grey(0.6))+
    ggplot2::geom_line(data = to_plot, ggplot2::aes(x = Year, y = Index)) +
    ggplot2::geom_ribbon(data = to_plot, ggplot2::aes(x = Year, ymin = lci, ymax = uci), alpha = 0.12)+
    ggplot2::scale_x_continuous(breaks = yys)+
    ggplot2::scale_y_continuous(limits = c(0,NA))+
  geofacet::facet_geo(facets = ~ prst,grid = facets,scales = "free_y", label = "code")
  #geom_text_repel(data = labsbcr, aes(x = year, y = index,label = BCR),size = 2)
  }else{

}

    return(ptraj)

}#end function















# indt$prst = gsub(str_extract(indt$stratcode,"-(.*)-"),pattern = "-",replacement = "",fixed = T)
# indt$prst = as.character(factor(indt$prst,levels = unique(stprovfacet$code)))
indt = tpout
indt$state = toTitleCase(tolower(indt$state))
indt$prst = as.character(factor(indt$state,levels = unique(stprovfacet$name)))
labsbcr = indt[which(indt$year == max(indt$year,na.rm = T)),]

cols = function(x){
  cl = "stable"
  if(x > 1){cl = "inc"}
  if(x < 0.5 & x > 0.25){cl = "dec"}
  if(x < 0.25){cl = "Ldec"}

  return(cl)
}

for(pp in labsbcr$region){
  indt[which(indt$region == pp),"col"] = cols(labsbcr[which(labsbcr$region == pp),"index"])
}



pdf(file = paste0(outdir,"Grassland indicator geofacet plot by stratum.pdf"),
    height = 8.5,width = 11)
print(ptraj)
dev.off()
# for(p in stprovfacet$code)){
#
# }#p







