#' Generate a geofacet plot of population trajectories by province/state
#'
#' \code{geofacet_plot} allows you to generate a faceted plot of population trajectories
#'   for each strata by province/state. Given a model stratified by "state", "bbs_cws", or "bbs_usgs"
#'   and indices generated by \code{generate_strata_indices} or \code{generate_regional_indices}, this
#'   function will generate a faceted plot showing the population trajectories. All geofacet plots have
#'   one facet per state/province, so if strata-level indices from the "bbs_cws" or "bbs_usgs" are given,
#'   the function plots multiple trajectories (one for each of the relevant strata) within each facet.
#'
#' @param indices_list Dataframe of strata or state/province indices produced by
#'   \code{generate_strata_indices} or \code{generate_regional_indices}
#' @param stratify_by How were the data stratified?
#' @param multiple Logical, if TRUE, multiple strata-level trajectories are plotted within each prov/state facet
#' @param trends Optional dataframe of matching strata or state/province trends produced by
#'   \code{generate_strata_trends} or \code{generate_regional_trends}. If included trajectories are coloured based on the same
#'   colour scale used in \code{generate_map}
#' @param slope Optional Logical, if dataframe of trends is included, colours in the plot are based on slope trends, Default = FALSE
#' @param add_observed_means Should the facet plots include points indicating the observed mean counts. Defaults to FALSE.  Note: scale of observed means and annual indices may not match due to imbalanced sampling among strata
#' @param species Species name to be added onto the plot
#' @param ci_width quantile to define the width of the plotted credible interval. Defaults to 0.95, lower = 0.025 and upper = 0.975
#'
#'
#'
#' @return ggplot object
#'
#' @importFrom ggplot2 ggplot theme element_blank element_line
#' labs geom_line geom_ribbon aes element_text element_rect
#' @importFrom grDevices grey
#' @importFrom geofacet facet_geo
#' @importFrom ggrepel geom_text_repel
#'
#' @examples
#'
#' \dontrun{
#' # Set stratification type for future use
#' stratification <- "bbs_cws"
#'
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = stratification)
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Canada Warbler",
#'                                   model = "gam")
#' mod <- run_model(jags_data = prepped_data)
#'
#' #Generate the indices for each strata
#' strata_index <- generate_strata_indices(jags_mod = mod)
#'
#' # Get the data frame of trends by strata
#' trend <- generate_strata_trends(indices = strata_index)
#'
#' # Obtain a map of the trends by each strata
#' map <- geofacet_plot(indices = strata_index, trend = trend, stratify_by = stratification)
#' }
#' @export
#'



geofacet_plot <- function(indices_list = NULL,
                          stratify_by = NULL,
                          ci_width = 0.95,
                          multiple = FALSE,
                          trends = NULL,
                          slope = FALSE,
                          add_observed_means = FALSE,
                          species = ""){

  if (is.null(stratify_by))
  {
    stop("Argument stratify_by is empty."); return(NULL)
  }

  if (is.null(indices_list))
  {
    stop("Argument indices_list is empty. Please supply indices from generate_strata_indices() or generate_regional_indices()"); return(NULL)
  }

  alpha_ribbon = 0.5

  facets <- utils::read.csv(system.file("geofacet-grids", strata[[stratify_by]], package = "bbsBayes"),stringsAsFactors = F)

  indices = indices_list$data_summary
  lq = (1-ci_width)/2
  uq = ci_width+lq
  lqc = paste0("Index_q_",lq)
  uqc = paste0("Index_q_",uq)


  indices$lci = indices[,lqc]
  indices$uci = indices[,uqc]


  mny = min(indices$Year)
  mxy = max(indices$Year)
  yys = seq(mny,mxy,length.out = 3)


  uplim = max(indices$Index)

  if(multiple){

     #
     # indices$code = indices$Region
     #




  }else{

    indices$code = indices$Region

    map_palette <- c("#313695")

    if(!is.null(trends)){

      trends$code = trends$Region
      breaks <- c(-7, -4, -2, -1, -0.5, 0.5, 1, 2, 4, 7)

      if(slope){
        trends$Trend <- trends$Slope_Trend
      }
      trends$Trendcat <- cut(trends$Trend, breaks = c(-Inf, breaks, Inf),ordered_result = T)

      map_palette <- c("#a50026", "#d73027", "#f46d43", "#fdae61", "#fee090", "#ffffbf",
                       "#e0f3f8", "#abd9e9", "#74add1", "#4575b4", "#313695")
      names(map_palette) <- levels(trends$Trendcat)
      indices <- merge(indices,trends[,c("Region","Trend","Trendcat")],by = "Region")
      trlabs = indices[which(indices$Year == yys[2]),]
      trlabs$Trend = paste(signif(round(trlabs$Trend,1),2),"%/yr")


       }else{

      indices$Trendcat = factor(rep("#313695",nrow(indices),levels = map_palette))
      }


      ptraj <- ggplot2::ggplot(data = indices) +
        ggplot2::theme(panel.grid.major = ggplot2::element_blank(),
                       panel.grid.minor = ggplot2::element_blank(),
                       panel.background = ggplot2::element_blank(),
                       axis.text = ggplot2::element_text(colour = grey(0.2)),
                       strip.background = ggplot2::element_rect(fill = grDevices::grey(0.97)),#strcol #, colour = grey(0.9), size = NULL, linetype = NULL, color = NULL, inherit.blank = FALSE
                       #axis.line = element_line(colour = "black"),
                       legend.position = "none") +
        ggplot2::labs(title = paste(species,"trajectories within Provinces and States"), x = "", y = "Annual indices") +

        ggplot2::geom_line(data = indices, ggplot2::aes(x = Year, y = Index),colour = grDevices::grey(0.6)) +
#        ggplot2::geom_line(data = indices, ggplot2::aes(x = Year, y = Index,colour = Trendcat)) +
        ggplot2::geom_ribbon(data = indices, ggplot2::aes(x = Year, ymin = lci, ymax = uci,fill = Trendcat), alpha = alpha_ribbon)+
        ggplot2::scale_x_continuous(breaks = yys)+
        ggplot2::coord_cartesian(ylim = c(0,uplim))+
        ggplot2::scale_colour_manual(values = map_palette, aesthetics = c("colour","fill"))


       if(add_observed_means){
        ptraj <- ptraj+
          ggplot2::geom_point(data = indices,ggplot2::aes(x = Year,y = obs_mean),colour = grDevices::grey(0.6),size = 0.5, alpha = alpha_ribbon)
      }

      if(!is.null(trends)){
        ptraj <- ptraj+
          #ggrepel::geom_text_repel(data = trlabs, mapping = ggplot2::aes(x = Year,y = uci,label = Trend,colour = Trendcat), size = 3,nudge_y = 0.2*uplim,segment.alpha = 0.1)
        ggrepel::geom_text_repel(data = trlabs, mapping = ggplot2::aes(x = Year,y = uci,label = Trend),colour = grDevices::grey(0.6), size = 2,nudge_y = 0.2*uplim,segment.alpha = 0.1)
      }


        ptraj <- ptraj+geofacet::facet_geo(facets = ~ code,grid = facets,label = "code")




  }

     return(ptraj)

}#end function

















