#' Obtain MCMC list from jagsUI object
#'
#' \code{get_mcmc_list} will return both the \code{mcmc.list} object
#'   and the \code{sims.list} object from jagsUI. \code{mcmc.list}
#'   is a list of the MCMC samples generated by the rjags library,
#'   and \code{sims.list} is a vectorized version of \code{mcmc.list}
#'   produced by the jagsUI library.
#'
#' @param jags_mod JAGS object returned by \code{run_model}
#'
#' @return List containing:
#' \item{mcmc_list}{MCMC samples produced by rjags}
#' \item{sims_list}{Vectorized posterior samples produced by jagsUI}
#'
#' @export
#'
#' @examples
#'
#' \dontrun{
#' # Run a JAGS model analysis on a species
#' stratified_data <- stratify(bbs_data = fetch_bbs_data(), stratify_by = "bcr")
#' prepped_data <- prepare_jags_data(strat_data = stratified_data,
#'                                   species_to_run = "Barn Swallow",
#'                                   model = "slope")
#' mod <- run_model(jags_data = prepped_data)
#'
#' # Get the posterior samples from that model
#' samples <- get_mcmc_list(jags_mod = mod)
#' }
#'

get_mcmc_list <- function(jags_mod = NULL)
{
  return(list(mcmc_list = jags_mod$samples,
              sims_list = jags_mod$sims.list))
}
