#' Create geofacet plot of population trajectories by province/state
#'
#' Generate a faceted plot of population trajectories for each strata by
#' province/state. Given a model stratified by "state", "bbs_cws", or "bbs_usgs"
#' and indices generated by `generate_indices()` this function will generate a
#' faceted plot showing the population trajectories. All geofacet plots have one
#' facet per state/province, so if strata-level indices from the "bbs_cws" or
#' "bbs_usgs" are given, the function plots multiple trajectories (one for each
#' of the relevant strata) within each facet.
#'
#' @param multiple Logical, if TRUE, multiple strata-level trajectories are
#'   plotted within each prov/state facet
#' @param trends List. (Optional) Output generated by `generate_trends()`. If
#'   included trajectories are coloured based on the same colour scale used in
#'   `plot_map`
#' @param slope Logical. If dataframe of trends is included, whether colours in
#'   the plot should be based on slope trends. Default = FALSE
#' @param add_observed_means Should the facet plots include points indicating
#'   the observed mean counts. Defaults to FALSE.  Note: scale of observed means
#'   and annual indices may not match due to imbalanced sampling among strata
#' @param ci_width quantile to define the width of the plotted credible
#'   interval. Defaults to 0.95, lower = 0.025 and upper = 0.975
#' @param col_viridis Logical flag to use "viridis" colour-blind friendly
#'   palette. Default is `FALSE`
#' @param indices_list Deprecated. Use `indices` instead
#' @param stratify_by Defunct.
#' @param species Defunct.
#' @param select Defunct.
#'
#' @inheritParams common_docs
#'
#' @return ggplot object
#'
#' @examples
#'
#' # Using the example model for Pacific Wrens...
#'
#' # Generate indices
#' i <- generate_indices(pacific_wren_model,
#'                       regions = c("stratum", "prov_state"))
#' # Generate trends
#' t <- generate_trends(i)
#'
#' # Now make the geofacet plot.
#' plot_geofacet(i, trends = t, multiple = TRUE)
#' plot_geofacet(i, trends = t, multiple = TRUE, col_viridis = TRUE)
#' plot_geofacet(i, multiple = TRUE)
#' plot_geofacet(i, trends = t, multiple = FALSE)
#' plot_geofacet(i, multiple = FALSE)
#'
#' # With different ci_width, specify desired quantiles in indices
#' i <- generate_indices(pacific_wren_model,
#'                       regions = c("stratum", "prov_state"),
#'                       quantiles = c(0.005, 0.995))
#'
#' plot_geofacet(i, multiple = FALSE, ci_width = 0.99)
#'
#' @export


plot_geofacet <- function(indices,
                          ci_width = 0.95,
                          multiple = FALSE,
                          trends = NULL,
                          slope = FALSE,
                          add_observed_means = FALSE,
                          col_viridis = FALSE,
                          indices_list, stratify_by, species, select) {

  # Deprecated/Defunct args
  if(!missing(indices_list)) {
    dep_warn("3.0.0", "indices_list", "`indices`")
    indices <- indices_list
  }

  if(!missing(stratify_by)) dep_stop("3.0.0", "stratify_by")
  if(!missing(species)) dep_stop("3.0.0", "species")
  if(!missing(select)) dep_stop("3.0.0", "select")

  # Checks
  check_data(indices)
  check_logical(multiple, slope, add_observed_means, col_viridis)
  check_numeric(ci_width)
  check_range(ci_width, c(0.001, 0.999))

  stratify_by <- indices[["meta_data"]]$stratify_by

  if(!"prov_state" %in% names(indices$meta_strata)) {
    stop("Cannot create geofacet plots for data which doesn't align with ",
         "provincial/state boundaries.\n  `indices` from `generate_indices()` ",
         "must have had `prov_state` in the regions.", call. = FALSE)
  } else if(multiple & !"stratum" %in% names(indices$meta_strata)) {
    stop("Cannot create mutliple plots per geofacet if `stratum` was not a ",
         "region used in `generate_indices()`", call. = FALSE)
  }

  alpha_ribbon <- 0.5
  r <- dplyr::if_else(multiple, "stratum", "prov_state")

  species <- indices[["meta_data"]]$species
  stratify_by <- indices[["meta_data"]]$stratify_by
  meta_strata <- indices[["meta_strata"]]

  # Check trends if present
  if(!is.null(trends)) {

    check_data(trends)

    if(any(unlist(trends$meta_data) != unlist(indices$meta_data))) {
      stop("`trends` data must have been created from the same `indices` ",
           "used here.\n",
           "Meta data doesn't match (see `",
           deparse(substitute(trends)), "[['meta_data']]` vs. `",
           deparse(substitute(indices)), "[['meta_data']]`)",
           call. = FALSE)
    }

    check_slope(trends[["trends"]], slope)
    tr <- TRUE
    trends <- dplyr::filter(trends[["trends"]], .data$region_type == .env$r)

  } else tr <- FALSE

  indices <- indices[["indices"]] %>%
    dplyr::filter(.data$region_type == .env$r) %>%
    calc_luq(ci_width)

  if(stratify_by == "bbs_cws") by <- "bbs_cws" else by <- "bbs_usgs"
  facets <- load_internal_file("geofacet-grids", by)

  min_year <- min(indices$year)
  max_year <- max(indices$year)
  years <- as.integer(seq(min_year, max_year, length.out = 3))

  uplim <- max(indices$index, na.rm = TRUE)

  # Multiple regions per plot
  if(multiple) {
    if(tr) trends <- trends %>%
        dplyr::inner_join(meta_strata, by = c("region" = "strata_name"))

    indices <- indices %>%
      dplyr::inner_join(meta_strata, by = c("region" = "strata_name")) %>%
      dplyr::mutate(code = .data$prov_state,
                    group = .data$region)
  } else {
    indices <- indices %>%
      dplyr::mutate(code = .data$region,
                    group = 1)
  }

  # Trends
  if(tr) {
    breaks <- c(-7, -4, -2, -1, -0.5, 0.5, 1, 2, 4, 7)
    if(slope) trends$trend <- trends$slope_trend

    indices <- trends %>%
      dplyr::select("region", "trend") %>%
      dplyr::mutate(trend_cat = cut(
        .data$trend, breaks = c(-Inf, breaks, Inf), ordered_result = TRUE)) %>%
      dplyr::inner_join(indices, by = "region") %>%
      dplyr::arrange(.data$region, .data$year)

  } else {
    indices <- dplyr::mutate(indices, trend = 0, trend_cat = "no_trends")
  }

  # Labels
  tr_labs <- indices %>%
    dplyr::filter(.data$year == .env$years[2]) %>%
    dplyr::mutate(t_fmt = signif(round(.data$trend, 1), 2),
                  extra = "")

  if(stratify_by %in% c("bbs_usgs", "bbs_cws")){
    tr_labs <- dplyr::mutate(
      tr_labs,
      extra = paste0("BCR", stringr::str_extract(.data$region, "[0-9]{1,2}$")))
  }

  tr_labs <- dplyr::mutate(
    tr_labs,
    lbl = dplyr::case_when(
      !.env$multiple & !.env$tr ~ "",
      !.env$multiple &  .env$tr ~ paste(.data$t_fmt, "%/yr"),
      .env$multiple &  .env$tr ~ paste0(.data$t_fmt, " ", .data$extra),
      .env$multiple & !.env$tr ~ .data$extra))


  # Colours
  if(tr) n <- levels(indices$trend_cat) else n <- "no_trends"
  map_palette <- dplyr::case_when(
    !multiple ~ "#313695",
    multiple & !tr ~ "#39568c",
    col_viridis ~ c("#fde725", "#dce319", "#b8de29", "#95d840", "#73d055",
                    "#55c667", "#238a8d", "#2d708e", "#39568c", "#453781",
                    "#481567"),
    TRUE ~ c("#a50026", "#d73027", "#f46d43", "#fdae61", "#fee090", "#ffffbf",
             "#e0f3f8", "#abd9e9", "#74add1", "#4575b4", "#313695")) %>%
    stats::setNames(n)

  # Plot
  p <- ggplot2::ggplot(data = indices) +
    ggplot2::theme(
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.background = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_text(
        colour = "grey20", size = 5, angle = 90),
      axis.text.y = ggplot2::element_text(colour = "grey20", size = 5),
      strip.background = ggplot2::element_rect(fill = "grey97"),
      strip.text = ggplot2::element_text(size = 6, margin = ggplot2::margin()),
      legend.position = "none") +
    ggplot2::labs(title = paste(
      species, "trajectories within Provinces and States"),
      x = "", y = "Annual indices") +
    ggplot2::geom_line(
      ggplot2::aes(x = .data$year, y = .data$index, group = .data$group),
      colour = "grey60") +
    ggplot2::geom_ribbon(
      ggplot2::aes(x = .data$year, ymin = .data$lci, ymax = .data$uci,
                   group = .data$group, fill = .data$trend_cat),
      alpha = alpha_ribbon) +
    ggrepel::geom_text_repel(
      data = tr_labs,
      ggplot2::aes(x = .data$year, y = .data$uci, label = .data$lbl,
                   group = .data$group),
      colour = "grey60", size = 2, nudge_y = 0.2 * uplim,
      segment.alpha = 0.1) +

    ggplot2::scale_x_continuous(breaks = years) +
    ggplot2::coord_cartesian(ylim = c(0, uplim)) +
    ggplot2::scale_fill_manual(values = map_palette)

  # Add subtitle with year range
  if(tr) {
    if(slope) t <- "slope-based trends" else t <- "trends"
    p <- p + ggplot2::labs(subtitle = paste0("with ", t, " (calulated for ",
                                             unique(trends$start_year), "-",
                                             unique(trends$end_year), ")"))
  }


  if(add_observed_means){
    p <- p +
      ggplot2::geom_point(
        ggplot2::aes(x = .data$year, y = .data$obs_mean, group = .data$group),
        colour = "grey60", size = 0.5, alpha = alpha_ribbon, na.rm = TRUE)
  }

  # Add final geofacetting

  # Suppress messages due to custom grid
  suppressMessages(
    p + geofacet::facet_geo(facets = ~code, grid = facets, label = "code"))
}



























