#' Calculate Watanabe–Akaike information criterion
#'
#' \code{waic} returns the Watanabe–Akaike information criterion (WAIC) for the
#'   supplied model. WAIC is a generalization of the Akaike information
#'   criterion onto singular statistical model.
#'
#'   NOTE: in order to calculated WAIC, the model MUST track the parameter
#'   "lambda". In species that are data-rich, such as Barn Swallow,
#'   this produces extremely large JAGS objects, and takes up a considerable
#'   amount of memory when simulating with \code{run_model}
#'
#'   See examples for details.
#'
#' @param jags_data Data prepared by \code{prepare_jags_data}, used
#'   for input to the JAGS model
#' @param jags_mod JAGS list generated by \code{run_model}
#'
#' @return Double precision numerical value
#'
#' @export
#'
#' @examples
#'
#' \dontrun{
#'   # Run a JAGS model, and be sure to track the parameter "lambda"
#'   jags_mod <- run_model(jags_data = prepared_data,
#'                         variable_names = "lambda")
#'
#'   # Output WAIC
#'   waic(jags_mod)
#' }
#'

waic <- function(jags_data = NULL,
                 jags_mod = NULL)
{
  lppd_sum <- lppd(jags_data = jags_data, jags_mod = jags_mod)
  pwaic_sum <- p_waic(jags_data = jags_data, jags_mod = jags_mod)

  return(-2 * (lppd_sum - pwaic_sum))
}
